# Generated by Django 6.0.3 on 2026-03-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
