# Generated by Django 6.0.3 on 2026-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='referral_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
