# Generated by Django 6.0.3 on 2026-04-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cartitems_referral_code_orderitem_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='is_wishlist',
            field=models.BooleanField(default=True),
        ),
    ]
