# Generated by Django 6.0.3 on 2026-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_wishlist_is_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
