# Generated by Django 6.0.3 on 2026-04-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
