# Generated by Django 6.0.3 on 2026-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_enrollment_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
