# Generated by Django 6.0.3 on 2026-03-17 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.affiliate'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
