# Generated by Django 6.0.3 on 2026-03-24 03:11

import apps.affiliates.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='total_earnings',
            new_name='total_earned',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='affiliate',
            name='referral_code',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='affiliate_type',
            field=models.CharField(choices=[('affiliate', 'Affiliate'), ('external_affiliate', 'External Affiliate'), ('territorial_orientation_center', 'Territorial Orientation Center')], default='affiliate', max_length=50),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='id',
            field=models.CharField(default=apps.affiliates.models.generate_affiliate_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'affiliate'}, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='affiliate',
            index=models.Index(fields=['status'], name='affiliates__status_047e5a_idx'),
        ),
    ]
