# Generated by Django 6.0.3 on 2026-04-05 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_rename_total_earnings_affiliate_total_earned_and_more'),
        ('courses', '0017_remove_lecturecaption_lecture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('referral_url', models.URLField(blank=True, null=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='affiliates.affiliate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='courses.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('affiliate', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AffiliateReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('session_key', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_converted', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_clicks', to='affiliates.affiliate')),
                ('affiliate_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='affiliates.affiliatecourselink')),
                ('clicked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliate_clicks', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_clicks', to='courses.course')),
            ],
            options={
                'ordering': ['-clicked_at'],
            },
        ),
    ]
