# Generated by Django 6.0.3 on 2026-04-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_affiliatecourselink_affiliatereferralclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=5),
        ),
    ]
