# Generated by Django 6.0.3 on 2026-04-06 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_affiliate_commission_rate'),
        ('courses', '0017_remove_lecturecaption_lecture_and_more'),
        ('orders', '0006_cartitems_referral_code_orderitem_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatecommission',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_commissions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='affiliatecommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_records', to='affiliates.affiliate'),
        ),
        migrations.AlterField(
            model_name='affiliatecommission',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='affiliatereferralclick',
            name='affiliate_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.affiliatecourselink'),
        ),
        migrations.AlterField(
            model_name='affiliatereferralclick',
            name='clicked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='affiliatereferralclick',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='affiliatereferralclick',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='affiliatereferralclick',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
