# Generated by Django 6.0.3 on 2026-04-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_affiliatecommission_order_affiliatecommission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliatecommission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
