# Generated by Django 6.0.3 on 2026-04-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0007_alter_affiliatecommission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
