# Generated by Django 6.0.3 on 2026-03-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='instructor_photos/')),
                ('instructor_type', models.CharField(choices=[('organization', 'Organization'), ('freelancer', 'Freelancer')], default='freelancer', max_length=20)),
            ],
            options={
                'db_table': 'instructor_profiles',
            },
        ),
    ]
