# Generated by Django 6.0.3 on 2026-04-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructor_delete_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
