# Generated by Django 6.0.3 on 2026-04-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0005_instructor_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='is_organization_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
