# Generated by Django 6.0.3 on 2026-04-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_instructor_is_organization_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
