# Generated by Django 6.0.3 on 2026-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('featured', 'Featured')], default='draft', max_length=20),
        ),
    ]
