# Generated by Django 6.0.3 on 2026-03-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='notes_text',
        ),
        migrations.AddField(
            model_name='lecture',
            name='LectureAttachment',
            field=models.FileField(blank=True, null=True, upload_to='lectures/attachments/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='LectureNoteFile',
            field=models.FileField(blank=True, null=True, upload_to='lectures/notes/'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/'),
        ),
    ]
