# Generated by Django 6.0.3 on 2026-03-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('featured', 'Featured'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
