# Generated by Django 6.0.3 on 2026-03-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_status'),
        ('orders', '0003_cart_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='course',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='orders.coupon'),
        ),
    ]
