# Generated by Django 6.0.3 on 2026-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_coupon_code_course_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='expiry_type',
            field=models.CharField(choices=[('1_week', '1 Week'), ('1_month', '1 Month'), ('3_months', '3 Months'), ('lifetime', 'Lifetime')], default='1_week', max_length=20),
        ),
    ]
