# Generated by Django 6.0.3 on 2026-03-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_coupon_alter_course_expiry_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='coupon',
            new_name='coupon_code',
        ),
    ]
