# Generated by Django 6.0.3 on 2026-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_rename_coupon_course_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
