# Generated by Django 6.0.3 on 2026-03-31 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_quizattempt_lectureprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectureProgress',
            new_name='LecturesProgress',
        ),
    ]
