# Generated by Django 6.0.3 on 2026-04-01 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_rename_lectureprogress_lecturesprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturesprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesprogress',
            name='last_watched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lecturesprogress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question')),
            ],
        ),
    ]
