# Generated by Django 6.0.3 on 2026-04-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_lecturesprogress_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True or False')], default='mcq', max_length=20),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
