# Generated by Django 6.0.3 on 2026-04-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_question_question_type_delete_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturecaption',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecturenotefile',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='lecturevideo',
            name='lecture',
        ),
        migrations.DeleteModel(
            name='LectureAttachment',
        ),
        migrations.DeleteModel(
            name='LectureCaption',
        ),
        migrations.DeleteModel(
            name='LectureNoteFile',
        ),
        migrations.DeleteModel(
            name='LectureVideo',
        ),
    ]
