# Generated by Django 6.0.3 on 2026-04-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessionRecordUploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('session_title', models.CharField(max_length=255)),
                ('recording_file', models.FileField(upload_to='live_classes/recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_recordings', to='courses.course')),
            ],
        ),
    ]
