# Generated by Django 6.0.3 on 2026-04-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_sessionrecorduploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionrecorduploader',
            old_name='section',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='sessionrecorduploader',
            old_name='coursename',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='sessionrecorduploader',
            old_name='session_title',
            new_name='title',
        ),
    ]
