# Generated by Django 6.0.3 on 2026-04-11 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_coursereviewhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereviewhistory',
            options={'ordering': ['-reviewed_at']},
        ),
        migrations.RenameField(
            model_name='coursereviewhistory',
            old_name='created_at',
            new_name='reviewed_at',
        ),
    ]
