# Generated by Django 6.0.3 on 2026-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_notes',
            field=models.TextField(blank=True),
        ),
    ]
