# Generated by Django 6.0.3 on 2026-04-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_lecture_lecture_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.lecture'),
        ),
    ]
