# Generated by Django 6.0.3 on 2026-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_comment_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
