# Generated by Django 6.0.3 on 2026-04-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_liveclass_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
