# Generated by Django 6.0.3 on 2026-06-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_liveclass_is_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
