# Generated by Django 6.0.3 on 2026-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawal',
            options={},
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='wallet',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_last4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='stripe_payout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdraw_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdraw_method',
            field=models.CharField(choices=[('bank_account', 'Bank Account'), ('debit_card', 'Debit Card'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
