# Generated by Django 6.0.3 on 2026-04-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_remove_verificationcode_user_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
