# Generated by Django 6.0.3 on 2026-04-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_stripe_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_id',
        ),
    ]
