# Generated by Django 6.0.3 on 2026-04-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Platform Owner'), ('Or_admin', 'Or_Admin'), ('manager', 'Manager'), ('reviewer', 'Reviewer'), ('finance', 'Finance'), ('student', 'Student'), ('instructor', 'Instructor'), ('member', 'Member'), ('affiliate', 'Affiliate')], db_index=True, default='student', max_length=30),
        ),
    ]
