# Generated by Django 6.0.3 on 2026-04-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
