# Generated by Django 6.0.3 on 2026-05-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aichatconversation',
            new_name='analytics_a_user_id_9d18b8_idx',
            old_name='analytics_a_user_id_1ce5c6_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatconversation',
            new_name='analytics_a_updated_82e8cf_idx',
            old_name='analytics_a_updated_369f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='aichatmessage',
            new_name='analytics_a_convers_03ae20_idx',
            old_name='analytics_a_convers_0ce476_idx',
        ),
    ]
