# Generated by Django 6.0.3 on 2026-03-24 03:11

import apps.organizations.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('instructor', 'Instructor'), ('finance', 'Finance'), ('reviewer', 'Reviewer')], default='instructor', max_length=30)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.organizations.models.default_expiry)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('instructor', 'Instructor'), ('finance', 'Finance'), ('reviewer', 'Reviewer')], default='instructor', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', '-joined_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='memberinvitation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='memberinvitation',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='memberinvitation',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='team',
            name='invited_by',
        ),
        migrations.RemoveField(
            model_name='team',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='owner',
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Public contact email', max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Verified organizations get priority'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_verified'], name='organizatio_is_veri_2607da_idx'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='organizations.membership'),
        ),
        migrations.DeleteModel(
            name='MemberInvitation',
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'email'), name='unique_pending_invitation'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['organization', 'user'], name='organizatio_organiz_631c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_user'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
