# Generated by Django 6.0.3 on 2026-04-06 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_invitation_membership_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at']},
        ),
    ]
