# Generated by Django 6.0.3 on 2026-04-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_invitation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
