# Generated by Django 6.0.3 on 2026-05-11 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='revenue_share',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
