# Generated by Django 6.0.3 on 2026-05-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_contract_revenue_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
    ]
