# Generated by Django 6.0.3 on 2026-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('Or-instructor', 'Or-Instructor'), ('finance', 'Finance'), ('reviewer', 'Reviewer')], default='Or-instructor', max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('Or-instructor', 'Or-Instructor'), ('finance', 'Finance'), ('reviewer', 'Reviewer')], default='Or-instructor', max_length=30),
        ),
    ]
